export const imageMap: Record<string, string> = {
  a: "/images/a.webp",
  logo1: "/images/logo1.png",
  logo2: "/images/logo2.png",
  logo3: "/images/logo3.jpg",
  e: "/images/e.webp",
  b: "/images/b.webp",
  c: "/images/c.webp",
  d: "/images/d.webp",
  f: "/images/f.webp",
  g: "/images/g.webp",
  h: "/images/h.webp",
  i: "/images/i.png",
  j: "/images/j.png",
  k: "/images/k.webp",
  l: "/images/l.jpg",
  m: "/images/m.webp",
  n: "/images/teams/2055x_team.webp",
  q: "/images/q.JPG",
  t: "/images/t.jpeg",
  u: "/images/u.JPG",
};

export type TimelineItem = {
  title: string;
  location: string;
  date: string;
  imgKey?: string;
  description?: string;
  award1?: string;
  award2?: string;
  award3?: string;
  navigatePath?: string;
};

export const items: TimelineItem[] = [
  {
    title: "Ontario HS Provincial Championship",
    location: "Ontario",
    date: "February 2026 ",
    imgKey: "u",
    description: "Awards:",
    award1: "   - Design Award",
    award2: "   - World Qualifier",
    navigatePath: "/achievements",
  },
  {
    title: "Gateway to the West VEX V5 Robotics Competition Signature Event",
    location: "West Virginia",
    date: "January 2026 ",
    description: "Awards:",
    award1: "   - Think Award",
  },
  {
    title: "Waterloo Showdown - A V5RC Push Back Qualifier",
    location: "Waterloo ON",
    date: "January 2026 ",
    imgKey: "q",
    description: "Awards:",
    award1: "   - Tournament Champions ",
    award2: "   - Think Award",
  },
  {
    title: "St. Catherine VRC Qualifier",
    location: "St. Catharines ON",
    date: "November 2025",
    description: "Awards:",
    award1: "   - Tournament Champion ",
    award2: "   - Think Award",
  },
  {
    title: "LAUNCH at EATON V5 Robotics Competition Signature Event",
    location: "Beachwood OH",
    date: "November 14th-15th, 2025 ",
    imgKey: "t",
    description: "Awards:",
    award1: "   - Think Award",
  },
  {
    title: "Gateway to the West VEX V5 Robotics Competition Signature Event",
    location: "Triadelphia WV",
    date: "January 29-30th, 2025 - Triadelphia WV",
    imgKey: "m",
    description: "Awards:",
    award1: "   - Think Award",
  },
  {
    title: "The RiverBots III VEX V5 Robotics Competition Signature Event",
    location: "Monroe MI",
    date: "December 13-14th & 15-16th, 2024 - Monroe MI",
    imgKey: "l",
    description: "Awards:",
    award1: "   - Think Award",
    navigatePath: "/achievements",
  },
  {
    title: "Glenforest iDESIGN 365 VEX V5 Robotics Competition",
    location: "Missisauga ON",
    date: "November 23, 2024 - Missisauga ON",
    imgKey: "j",
    description: "Awards:",
    award1: "   - Design Award ",
  },
  {
    title: "Highlander Summit VEX V5 Signature Event",
    location: "Newark NJ",
    date: "September 20-22nd, 2024 - Newark NJ",
    imgKey: "i",
    description: "Awards:",
    award1: "   - Think Award",
  },
  {
    title: "VEX AI World Championship",
    location: "Houston TX",
    date: "June 7-8th, 2024 - Houston TX",
    imgKey: "e",
    description: "Awards:",
    award1: "   - Robot Skills Champion ",
    award2: "   - Innovate Award ",
  },
  {
    title: "2024 VEX Robotics World Championship",
    location: "Dallas TX",
    date: "April 25-27th, 2024 - Dallas TX",
    imgKey: "b",
    description: "Awards:",
    award1: "   - Create Award ",
  },
  {
    title: "Battle of the Bots VRC Signature Event",
    location: "Bristol TN",
    date: "Febuary 9-10th, 2024 - Bristol TN",
    imgKey: "f",
    description: "Awards:",
    award1: "   - Robot Skills Champion ",
    award2: "   - Think Award ",
  },
  {
    title: "Canadian Open VRC Signature Event",
    location: "Markham ON",
    date: "January 27-28th, 2024 - Markham ON",
    imgKey: "a",
    description: "Awards:",
    award1: "   - Think Award ",
  },
  {
    title: "Hollywood Blockbuster VRC Signature Event",
    location: "Los Angeles CA",
    date: "December 27-29th, 2023 - Los Angeles CA",
    imgKey: "g",
    description: "Awards:",
    award1: "   - Sportsmanship Award ",
  },
  {
    title: "VRC Over/Under Qualifier + Remote Judging and Notebooks",
    location: "Brampton ON",
    date: "December 16th, 2023 - Brampton ON",
    imgKey: "logo2",
    description: "Awards:",
    award1: "   - Excellence Award",
  },
  {
    title: "VRC Over/Under Qualifier + Remote Judging and Notebooks",
    location: "Brampton ON",
    date: "November 23rd, 2023 - Brampton ON",
    imgKey: "h",
    description: "Awards:",
    award1: "   - Tournament Champions",
    award2: "   - Think Award",
    navigatePath: "/achievements",
  },
  {
    title: "VEX Robotics Ontario VRC Provincial Championships 2023 (Remote Judging & Engineering Book Submission - 2055B)",
    location: "Niagara Falls ON",
    date: "March 5th, 2023 - Niagara Falls ON",
    imgKey: "",
    description: "Awards:",
    award1: "   - Innovate Award",
  },
  {
    title: "Canadian Open VRC Signature Event",
    location: "Markham ON",
    date: "Febuary 12th, 2023 - Markham ON",
    imgKey: "",
    description: "Awards:",
    award1: "   - Design Award",
  },
  {
    title: "Brampton Robotics VRC Qualifier and Skills",
    location: "Brampton ON",
    date: "January 23rd, 2023 - Brampton ON",
    imgKey: "",
    description: "Awards:",
    award1: "   - Tournament Finalists",
  },
];
