export const imageMap: Record<string, string> = {
  a: "/images/a.webp",
  logo1: "/images/logo1.png",
  logo2: "/images/logo2.png",
  logo3: "/images/logo3.jpg",
  e: "/images/e.webp",
  b: "/images/b.webp",
  c: "/images/c.webp",
  d: "/images/d.webp",
  f: "/images/f.webp",
  g: "/images/g.webp",
  h: "/images/h.webp",
  i: "/images/i.png",
  j: "/images/j.png",
  k: "/images/k.webp",
  l: "/images/l.jpg",
  m: "/images/m.webp",
  n: "/images/teams/2055x_team.webp",
  o: "/images/o.jpg",
  p: "/images/p.JPG",
  q: "/images/q.JPG",
  r: "/images/r.jpeg",
  s: "/images/s.jpeg",
};

export type TimelineItem = {
  title: string;
  location: string;
  date: string;
  imgKey?: string;
  description?: string;
  award1?: string;
  award2?: string;
  award3?: string;
  navigatePath?: string;
};

export const items: TimelineItem[] = [
  {
    title: "VEX Robotics World Championship",
    location: "Ontario",
    date: "Apr 25th-27th, 2026 - Ontario",
    imgKey: "s",
    description: "Awards:",
    award1: "   - Inspire Award ",
    navigatePath: "/achievements",
  },
  {
    title: "Ontario MS Provincial Championship",
    location: "Ontario",
    date: "Mar 1st 2026 - Ontario",
    imgKey: "r",
    description: "Awards:",
    award1: "   - Innovate Award ",
    award2: "   - World Qualifier",
    navigatePath: "/achievements",
  },
  {
    title: "Waterloo Showdown - A V5RC Push Back Qualifier",
    location: "Ontario",
    date: "Jan 2026 - Ontario",
    imgKey: "q",
    description: "Awards:",
    award1: "   - Tournament Champions",
    navigatePath: "/achievements",
  },
  {
    title: "White Oaks V5RC Qualifier",
    location: "Oakville ON",
    date: "November 2025 - Oakville ON",
    imgKey: "p",
    description: "Awards:",
    award1: "   - Innovate Award ",
    navigatePath: "/achievements",
  },
  {
    title: "Waterloo Throwdown - A V5RC Push Back Qualifier",
    location: "Waterloo ON",
    date: "November 2025 - Waterloo ON",
    imgKey: "o",
    description: "Awards:",
    award1: "   - Tournament Finalists ",
    award2: "   - Think Award ",
    navigatePath: "/achievements",
  },
  {
    title: "VEX Robotics World Championship",
    location: "Dallas TX",
    date: "May 9-11th, 2025 - Dallas TX",
    imgKey: "n",
    description: "Awards:",
    award1: "   - Design Award",
    navigatePath: "/achievements",
  },
  {
    title: "Gateway to the West VEX V5 Robotics Competition Signature Event",
    location: "Triadelphia WV",
    date: "January 29-30th, 2025 - Triadelphia WV",
    imgKey: "m",
    description: "Awards:",
    award2: "   - Judges Award (2055X)",
    navigatePath: "/achievements",
  },
  {
    title: "The RiverBots III VEX V5 Robotics Competition Signature Event",
    location: "Monroe MI",
    date: "December 13-14th & 15-16th, 2024 - Monroe MI",
    imgKey: "l",
    description: "Awards:",
    award1: "   - Design Award",
    navigatePath: "/achievements",
  },
  {
    title: "St. Catharines VEX V5 Robotics Competition Qualifier",
    location: "St. Catharines ON",
    date: "December 7, 2024 - St. Catharines ON",
    imgKey: "k",
    description: "Awards:",
    award1: "   - Innovate Award",
    navigatePath: "/achievements",
  },
  {
    title: "Ontario VRC Over/Under Provincial Championships",
    location: "Markham ON",
    date: "Febuary 23-24th, 2024 - Markham ON",
    imgKey: "c",
    description: "Awards:",
    award1: "   - Tournament Champions",
    award2: "   - World Qualifier",
    navigatePath: "/achievements",
  },
  {
    title: "iDESIGN Central Toronto VEX VRC Robotics Competition",
    location: "Toronto ON",
    date: "Febuary 10th, 2024 - Toronto ON",
    imgKey: "d",
    description: "Awards:",
    award1: "   - Build Award ",
    award2: "   - Tournament Champions ",
    navigatePath: "/achievements",
  },
  {
    title: "St. Catharines VRC Qualifier",
    location: "St. Catharines ON",
    date: "December 2nd, 2023 - St. Catharines ON",
    imgKey: "logo3",
    description: "Awards:",
    award1: "   - Tournament Finalists ",
    award2: "   - Think Award ",
    navigatePath: "/achievements",
  },
];
